-- Kora House — complete database setup.
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Paste the whole file into the Supabase SQL editor and run once.
--
-- RUN THIS ONCE, ON A FRESH PROJECT. It is not re-runnable: the tables, the
-- booking_status type, the triggers and the policies are all created without
-- guards, so a second run fails with "already exists". That is normal for
-- migrations, but it means a half-finished run cannot simply be repeated.
--
-- To start over on a project with no data you care about:
--     drop schema public cascade;
--     create schema public;
--     grant usage on schema public to anon, authenticated, service_role;
-- then paste this file again. That destroys every table in `public` —
-- do not run it against a database holding real bookings.

-- ===================================================================
-- 20260819120000_init.sql
-- ===================================================================

-- Kora House — initial schema
--
-- Design notes that matter, because they follow from how the house actually
-- operates rather than from a generic booking template:
--
--  1. THIS IS A REQUEST SYSTEM, NOT INSTANT BOOKING. The hosts talk to guests
--     before accepting ("we like to interact with guests to ensure our home is
--     the right fit"). So a guest submits a REQUEST, which starts as 'pending'
--     and only a host can move to 'confirmed'. Nothing a guest can do reserves
--     a room.
--
--  2. NO PRICING YET. Every nightly rate is still unconfirmed, so there is no
--     amount to charge and no payment table. `quoted_total` exists so a host
--     can record what they quoted, but the site never computes it.
--
--  3. Guest details are personal data. RLS is written so that anonymous users
--     can INSERT a request and can never SELECT one — including their own.
--     Without that, anyone could enumerate every guest's name, email and phone.

create extension if not exists "pgcrypto";   -- gen_random_uuid()
create extension if not exists "btree_gist"; -- needed for the exclusion constraint

-- ---------------------------------------------------------------- rooms ----

create table public.rooms (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique,
  room_number     int  not null unique,
  name            text not null,
  floor           text not null check (floor in ('Ground', 'First')),
  has_kitchenette boolean not null default false,
  -- Null until the hosts confirm. The site must not invent one.
  base_rate_inr   int,
  max_occupancy   int,
  is_active       boolean not null default true,
  sort_order      int not null default 0,
  created_at      timestamptz not null default now()
);

comment on column public.rooms.base_rate_inr is
  'Nightly rate in whole rupees. NULL means not yet confirmed — do not display a price while null.';

-- ------------------------------------------------------- booking requests ----

create type public.booking_status as enum ('pending', 'confirmed', 'declined', 'cancelled');

create table public.booking_requests (
  id             uuid primary key default gen_random_uuid(),
  reference      text not null unique,

  -- Stay
  check_in       date not null,
  check_out      date not null,
  adults         int  not null default 1 check (adults  between 1 and 12),
  children       int  not null default 0 check (children between 0 and 12),
  room_id        uuid references public.rooms(id) on delete set null,

  -- Guest
  guest_name     text not null check (length(btrim(guest_name)) between 2 and 120),
  guest_email    text not null check (guest_email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  guest_phone    text check (length(guest_phone) <= 40),
  guest_country  text check (length(guest_country) <= 80),
  message        text check (length(message) <= 2000),

  status         public.booking_status not null default 'pending',
  host_note      text,
  quoted_total_inr int,

  -- The stay as a range, kept in step with check_in/check_out by trigger.
  -- '[)' — check-out day is free for the next guest, which is how hotels work.
  stay           daterange generated always as (daterange(check_in, check_out, '[)')) stored,

  source         text not null default 'website',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint checkout_after_checkin check (check_out > check_in),
  constraint stay_not_absurdly_long  check (check_out - check_in <= 90)
);

-- A confirmed booking physically cannot overlap another confirmed booking for
-- the same room. Enforced by the database, not by application code, so a race
-- between two simultaneous confirmations cannot double-book.
alter table public.booking_requests
  add constraint no_overlapping_confirmed_stays
  exclude using gist (
    room_id with =,
    stay    with &&
  ) where (status = 'confirmed' and room_id is not null);

create index booking_requests_status_idx     on public.booking_requests (status, check_in);
create index booking_requests_stay_idx       on public.booking_requests using gist (stay);
create index booking_requests_created_at_idx on public.booking_requests (created_at desc);

-- ---------------------------------------------------------- blocked dates ----

-- Maintenance, family stays, or the house simply being closed.
create table public.blocked_dates (
  id         uuid primary key default gen_random_uuid(),
  -- Null room_id blocks the whole house.
  room_id    uuid references public.rooms(id) on delete cascade,
  starts_on  date not null,
  ends_on    date not null,
  reason     text,
  created_at timestamptz not null default now(),
  constraint block_ends_after_start check (ends_on > starts_on)
);

create index blocked_dates_range_idx on public.blocked_dates (starts_on, ends_on);

-- --------------------------------------------------------------- triggers ----

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger booking_requests_touch_updated_at
  before update on public.booking_requests
  for each row execute function public.touch_updated_at();

-- Human-readable reference: KH-2026-0417. Generated server-side so a guest
-- cannot choose or guess someone else's.
create or replace function public.set_booking_reference()
returns trigger
language plpgsql
as $$
declare
  candidate text;
  attempts  int := 0;
begin
  if new.reference is not null and new.reference <> '' then
    return new;
  end if;
  loop
    candidate := 'KH-' || to_char(now(), 'YYYY') || '-' ||
                 lpad((floor(random() * 10000))::int::text, 4, '0');
    exit when not exists (select 1 from public.booking_requests where reference = candidate);
    attempts := attempts + 1;
    if attempts > 25 then
      candidate := 'KH-' || to_char(now(), 'YYYY') || '-' || substr(gen_random_uuid()::text, 1, 6);
      exit;
    end if;
  end loop;
  new.reference := candidate;
  return new;
end;
$$;

create trigger booking_requests_set_reference
  before insert on public.booking_requests
  for each row execute function public.set_booking_reference();

-- A guest must never be able to submit something already accepted, nor edit a
-- decided request. Status transitions belong to hosts only.
create or replace function public.force_pending_on_insert()
returns trigger
language plpgsql
as $$
begin
  new.status := 'pending';
  new.host_note := null;
  new.quoted_total_inr := null;
  return new;
end;
$$;

create trigger booking_requests_force_pending
  before insert on public.booking_requests
  for each row execute function public.force_pending_on_insert();


-- ===================================================================
-- 20260819120050_staff.sql
-- ===================================================================

-- Who counts as staff.
--
-- Kept as an explicit allow-list table rather than "any authenticated user",
-- because Supabase projects usually have public sign-up enabled by default —
-- and if `authenticated` alone granted host powers, anyone who registered an
-- account could read every guest's contact details and confirm their own
-- booking. Membership of this table is the gate.

create table public.staff (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text,
  role       text not null default 'host' check (role in ('host', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.staff enable row level security;

-- SECURITY DEFINER so the check itself isn't subject to RLS on `staff`
-- (which would recurse). search_path is pinned — without it, a user-created
-- schema earlier on the path could shadow `staff` and spoof the answer.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.staff s where s.user_id = auth.uid()
  );
$$;

revoke all on function public.is_staff() from public;
grant execute on function public.is_staff() to authenticated;

-- Staff can see who else is staff; only admins can change the list.
create policy "staff read staff"
  on public.staff for select
  to authenticated
  using (public.is_staff());

create policy "admins manage staff"
  on public.staff for all
  to authenticated
  using (
    exists (select 1 from public.staff s where s.user_id = auth.uid() and s.role = 'admin')
  )
  with check (
    exists (select 1 from public.staff s where s.user_id = auth.uid() and s.role = 'admin')
  );

-- SETUP: after creating the first host account in Supabase Auth, run once —
--   insert into public.staff (user_id, email, role)
--   select id, email, 'admin' from auth.users where email = 'you@example.com';
-- Until a row exists here, nobody can read booking requests. That is the
-- intended default: closed, not open.


-- ===================================================================
-- 20260819120100_rls.sql
-- ===================================================================

-- Row Level Security.
--
-- The threat to keep in mind: `booking_requests` holds guests' names, emails
-- and phone numbers. Supabase exposes PostgREST directly to the browser with
-- the anon key, so any table left readable is readable BY EVERYONE — the anon
-- key is public by design and is in the JS bundle. RLS is the only thing
-- standing between an anonymous visitor and every guest's contact details.
--
-- Rules:
--   rooms            public read (the site needs it), staff write
--   blocked_dates    public read of the DATES only, via a view; staff write
--   booking_requests anon may INSERT and nothing else. No anon SELECT at all,
--                    not even of their own row — "their own" is unauthenticated
--                    and therefore unverifiable. The confirmation reference is
--                    returned by the API in the insert response instead.

alter table public.rooms            enable row level security;
alter table public.booking_requests enable row level security;
alter table public.blocked_dates    enable row level security;

-- Anything not matched by a policy is denied, so there is no default-allow.

-- ----------------------------------------------------------------- rooms ----

create policy "rooms are publicly readable"
  on public.rooms for select
  to anon, authenticated
  using (is_active);

create policy "staff manage rooms"
  on public.rooms for all
  to authenticated
  using (public.is_staff())
  with check (public.is_staff());

-- ------------------------------------------------------- booking requests ----

-- A visitor may lodge a request. They may not read, edit or delete anything.
-- The BEFORE INSERT triggers force status='pending' and clear host-only
-- columns, so a crafted payload cannot self-confirm or inject a host note.
create policy "anyone may submit a booking request"
  on public.booking_requests for insert
  to anon, authenticated
  with check (
    check_out > check_in
    and check_out - check_in <= 90
    -- No requests for dates already gone.
    and check_in >= current_date
    -- No requests absurdly far out.
    and check_in <= current_date + interval '2 years'
  );

-- Deliberately NO select policy for anon. Do not add one.

create policy "staff read booking requests"
  on public.booking_requests for select
  to authenticated
  using (public.is_staff());

create policy "staff update booking requests"
  on public.booking_requests for update
  to authenticated
  using (public.is_staff())
  with check (public.is_staff());

create policy "staff delete booking requests"
  on public.booking_requests for delete
  to authenticated
  using (public.is_staff());

-- ---------------------------------------------------------- blocked dates ----

create policy "staff manage blocked dates"
  on public.blocked_dates for all
  to authenticated
  using (public.is_staff())
  with check (public.is_staff());

-- Blocked dates are not public directly — a reason like "family staying" is
-- nobody's business. Availability is exposed through the function below, which
-- returns dates only.


-- ===================================================================
-- 20260819120200_availability.sql
-- ===================================================================

-- Availability.
--
-- Exposed as a function rather than a view over the tables, so the public
-- surface is exactly "is this room free on these dates" — never who booked it,
-- their contact details, or why a date is blocked ("family staying" is not the
-- internet's business).
--
-- Only CONFIRMED requests hold a room. Pending ones do not, deliberately: the
-- hosts decide, and a flood of speculative requests must not lock the calendar.

create or replace function public.room_availability(
  from_date date,
  to_date   date
)
returns table (
  room_id         uuid,
  slug            text,
  name            text,
  room_number     int,
  has_kitchenette boolean,
  is_available    boolean
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  with window_range as (
    select daterange(from_date, to_date, '[)') as r
  )
  select
    rm.id,
    rm.slug,
    rm.name,
    rm.room_number,
    rm.has_kitchenette,
    not (
      exists (
        select 1
        from public.booking_requests b, window_range w
        where b.room_id = rm.id
          and b.status  = 'confirmed'
          and b.stay && w.r
      )
      or exists (
        select 1
        from public.blocked_dates d, window_range w
        where (d.room_id = rm.id or d.room_id is null)
          and daterange(d.starts_on, d.ends_on, '[)') && w.r
      )
    ) as is_available
  from public.rooms rm
  where rm.is_active
  order by rm.sort_order, rm.room_number;
$$;

-- Callable by the public site. It reads the underlying tables as the caller
-- (security invoker), but returns only non-sensitive columns.
grant execute on function public.room_availability(date, date) to anon, authenticated;

-- The function reads booking_requests, which anon cannot SELECT under RLS.
-- A stable SECURITY DEFINER wrapper does the overlap test without ever
-- returning a row from that table.
create or replace function public.is_room_taken(p_room_id uuid, p_from date, p_to date)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.booking_requests b
    where b.room_id = p_room_id
      and b.status = 'confirmed'
      and b.stay && daterange(p_from, p_to, '[)')
  ) or exists (
    select 1 from public.blocked_dates d
    where (d.room_id = p_room_id or d.room_id is null)
      and daterange(d.starts_on, d.ends_on, '[)') && daterange(p_from, p_to, '[)')
  );
$$;

revoke all on function public.is_room_taken(uuid, date, date) from public;
grant execute on function public.is_room_taken(uuid, date, date) to anon, authenticated;

-- Rewritten to use the definer wrapper so it works for anonymous callers.
create or replace function public.room_availability(
  from_date date,
  to_date   date
)
returns table (
  room_id         uuid,
  slug            text,
  name            text,
  room_number     int,
  has_kitchenette boolean,
  is_available    boolean
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select
    rm.id,
    rm.slug,
    rm.name,
    rm.room_number,
    rm.has_kitchenette,
    not public.is_room_taken(rm.id, from_date, to_date) as is_available
  from public.rooms rm
  where rm.is_active
  order by rm.sort_order, rm.room_number;
$$;

grant execute on function public.room_availability(date, date) to anon, authenticated;


-- ===================================================================
-- 20260819120300_seed_rooms.sql
-- ===================================================================

-- Seed the six rooms.
--
-- Mirrors lib/rooms.ts, which stays the source of truth for the marketing
-- pages. Idempotent, so re-running a migration set is safe.
--
-- Rates are deliberately NULL. Nobody has confirmed them, and a placeholder
-- number in the database is exactly how a wrong price ends up quoted to a
-- guest. The site renders "Rate on request" while these are null.
--
-- Numbering is the hosts': facing the building, the rightmost upstairs room is
-- Room 1 and the leftmost is Room 5; the ground-floor room is Room 6.

insert into public.rooms (slug, room_number, name, floor, has_kitchenette, sort_order)
values
  ('zangskar',    1, 'Zangskar',    'First',  true,  1),
  ('deodar',      2, 'Deodar',      'First',  true,  2),
  ('chorten',     3, 'Chorten',     'First',  false, 3),
  ('dhauladhar',  4, 'Dhauladhar',  'First',  false, 4),
  ('butter-lamp', 5, 'Butter Lamp', 'First',  false, 5),
  ('mani',        6, 'Mani',        'Ground', false, 6)
on conflict (slug) do update
set room_number     = excluded.room_number,
    name            = excluded.name,
    floor           = excluded.floor,
    has_kitchenette = excluded.has_kitchenette,
    sort_order      = excluded.sort_order;


-- ===================================================================
-- 20260820100000_submit_booking_request.sql
-- ===================================================================

-- Submitting a booking request.
--
-- Why this function exists at all:
--
-- `INSERT ... RETURNING` requires a SELECT privilege on the returned columns,
-- and anon deliberately has no SELECT policy on booking_requests — that is the
-- single most important rule in this schema, because the table holds guests'
-- names, emails and phone numbers. So the obvious implementation (insert, then
-- read the generated reference back) is refused by RLS with 42501. Caught by
-- supabase/verify-live.mjs against the real project; a plain insert succeeds
-- and the identical insert with RETURNING does not.
--
-- The wrong fix is to add an anon SELECT policy. That would expose every guest
-- record to anyone holding the publishable key, which is everyone.
--
-- The right fix is this: a SECURITY DEFINER function whose return type is a
-- single text reference. It can write the row and read back that one value,
-- and there is no way to make it yield anything else. Same pattern as
-- is_room_taken() in 20260819120200_availability.sql.
--
-- Being SECURITY DEFINER, it bypasses RLS — so the date guards from the INSERT
-- policy are repeated here. They are the real enforcement for this path.

create or replace function public.submit_booking_request(
  p_check_in      date,
  p_check_out     date,
  p_adults        int,
  p_children      int,
  p_guest_name    text,
  p_guest_email   text,
  p_guest_phone   text default null,
  p_guest_country text default null,
  p_message       text default null,
  p_room_slug     text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room_id   uuid;
  v_reference text;
begin
  -- RLS does not run for a definer function, so these are not belt-and-braces;
  -- they are the only thing standing here.
  if p_check_out <= p_check_in then
    raise exception 'check_out must be after check_in' using errcode = '22023';
  end if;
  if p_check_out - p_check_in > 90 then
    raise exception 'stay too long' using errcode = '22023';
  end if;
  if p_check_in < current_date then
    raise exception 'check_in is in the past' using errcode = '22023';
  end if;
  if p_check_in > current_date + interval '2 years' then
    raise exception 'check_in too far ahead' using errcode = '22023';
  end if;

  -- Resolve the room from its slug in here. The caller never supplies an id,
  -- so it cannot point a request at an inactive or non-existent room.
  if p_room_slug is not null and btrim(p_room_slug) <> '' then
    select id into v_room_id
      from public.rooms
     where slug = p_room_slug and is_active
     limit 1;
  end if;

  -- Note what is absent from this insert: status, host_note, quoted_total_inr.
  -- There is no parameter for any of them, so self-confirmation is impossible
  -- by construction rather than by a trigger having to undo it.
  insert into public.booking_requests (
    check_in, check_out, adults, children, room_id,
    guest_name, guest_email, guest_phone, guest_country, message, source
  ) values (
    p_check_in, p_check_out, coalesce(p_adults, 1), coalesce(p_children, 0), v_room_id,
    btrim(p_guest_name), lower(btrim(p_guest_email)),
    nullif(btrim(coalesce(p_guest_phone, '')), ''),
    nullif(btrim(coalesce(p_guest_country, '')), ''),
    nullif(btrim(coalesce(p_message, '')), ''),
    'website'
  )
  returning reference into v_reference;

  return v_reference;
end;
$$;

-- `public` includes every future role; name the two that should have it.
revoke all on function public.submit_booking_request(
  date, date, int, int, text, text, text, text, text, text) from public;
grant execute on function public.submit_booking_request(
  date, date, int, int, text, text, text, text, text, text) to anon, authenticated;


-- ===================================================================
-- 20260821090000_booking_v2.sql
-- ===================================================================

-- Booking v2 — priced requests, host approval, then payment.
--
-- The shape, which is Airbnb's "Request to Book" rather than instant booking:
--
--   pending  -> guest asked. Holds nothing. Several people may ask for the
--               same dates; that is fine and deliberate.
--   accepted -> a host said yes and quoted a price. THIS HOLDS THE ROOM, on a
--               clock. The guest has settings.hold_hours to pay the deposit.
--   confirmed-> deposit received. The stay is real.
--   expired  -> accepted, but nobody paid in time. Room released automatically.
--   declined -> host said no. Nothing was ever charged, so nothing to refund.
--   cancelled-> called off after confirmation. Refund is a human decision.
--
-- Money never moves before a host has said yes. That is the whole point of the
-- design: declining someone costs nothing and needs no refund, which is what
-- makes it safe to actually vet guests rather than vet them theoretically.
--
-- All amounts are integer RUPEES. Not floats — money must never be a float.
-- Not paise either, despite Razorpay wanting paise: rupee amounts are what the
-- hosts quote and what guests read, and the ×100 happens at the Razorpay
-- boundary only (see lib/razorpay.ts). One unit, one place it changes.

-- --------------------------------------------------------------- settings ----

-- Single-row table. A key/value store would be more flexible and much worse:
-- these are typed, constrained values that the pricing engine depends on.
create table if not exists public.settings (
  id                  boolean primary key default true check (id),
  deposit_percent     int not null default 25 check (deposit_percent between 0 and 100),
  hold_hours          int not null default 24 check (hold_hours between 1 and 168),
  tax_percent         numeric(5,2) not null default 0 check (tax_percent >= 0 and tax_percent <= 50),
  currency            text not null default 'INR',
  min_nights          int not null default 1 check (min_nights between 1 and 30),
  cancellation_policy text,
  updated_at          timestamptz not null default now()
);

insert into public.settings (id) values (true) on conflict (id) do nothing;

comment on column public.settings.deposit_percent is
  'Percentage of the total taken online to hold the room. Balance is paid on arrival.';
comment on column public.settings.hold_hours is
  'How long an accepted request holds the room while awaiting the deposit.';

-- --------------------------------------------------------- rate overrides ----

-- Seasonal pricing. McLeodganj has a real high season, and a flat annual rate
-- would be wrong most of the year. Null room_id means "every room".
create table if not exists public.rate_overrides (
  id              uuid primary key default gen_random_uuid(),
  room_id         uuid references public.rooms(id) on delete cascade,
  starts_on       date not null,
  ends_on         date not null,
  nightly_rate_inr int not null check (nightly_rate_inr > 0),
  min_nights      int check (min_nights between 1 and 30),
  label           text,
  -- Higher wins when ranges overlap, so a specific event can sit on top of a
  -- broad season without having to carve the season up.
  priority        int not null default 0,
  created_at      timestamptz not null default now(),
  constraint override_ends_after_start check (ends_on > starts_on)
);

create index if not exists rate_overrides_lookup_idx
  on public.rate_overrides (starts_on, ends_on);

-- ------------------------------------------------- booking status rewrite ----

-- The exclusion constraint and the availability functions both reference the
-- enum, so they are dropped and rebuilt around the new type. Swapping the type
-- wholesale rather than using ALTER TYPE ... ADD VALUE is deliberate: a value
-- added by ALTER TYPE cannot be USED in the same transaction, which would make
-- this migration unrunnable as a single paste.
alter table public.booking_requests
  drop constraint if exists no_overlapping_confirmed_stays;

alter table public.booking_requests alter column status drop default;

do $$
begin
  if not exists (
    select 1 from pg_type t join pg_enum e on e.enumtypid = t.oid
     where t.typname = 'booking_status' and e.enumlabel = 'accepted'
  ) then
    create type public.booking_status_v2 as enum
      ('pending', 'accepted', 'confirmed', 'declined', 'cancelled', 'expired');

    alter table public.booking_requests
      alter column status type public.booking_status_v2
      using status::text::public.booking_status_v2;

    drop type public.booking_status;
    alter type public.booking_status_v2 rename to booking_status;
  end if;
end;
$$;

alter table public.booking_requests alter column status set default 'pending';

-- ------------------------------------------------------------ money on it ----

alter table public.booking_requests
  add column if not exists accepted_at      timestamptz,
  add column if not exists hold_expires_at  timestamptz,
  add column if not exists decided_by       uuid references auth.users(id) on delete set null,
  add column if not exists currency         text not null default 'INR',
  -- Snapshot of what each night cost when the quote was made. Kept so that
  -- changing a rate later never silently rewrites an existing quote.
  add column if not exists nightly_rates    jsonb,
  add column if not exists subtotal_inr     int check (subtotal_inr >= 0),
  add column if not exists tax_inr          int check (tax_inr >= 0),
  add column if not exists total_inr        int check (total_inr >= 0),
  add column if not exists deposit_inr      int check (deposit_inr >= 0),
  add column if not exists deposit_paid_at  timestamptz;

comment on column public.booking_requests.nightly_rates is
  'Per-night rate snapshot at quote time: [{"date":"2027-04-01","rate_inr":2500}]. Never recomputed.';

-- An accepted request holds the room just as firmly as a confirmed one — that
-- is what the guest is being asked to pay against. Leaving 'accepted' out of
-- this constraint would let two guests be quoted the same room at once, and
-- one of them would have paid for a room that was already gone.
alter table public.booking_requests
  add constraint no_overlapping_held_stays
  exclude using gist (
    room_id with =,
    stay    with &&
  ) where (status in ('accepted', 'confirmed') and room_id is not null);

-- --------------------------------------------------------------- payments ----

do $$
begin
  if not exists (select 1 from pg_type where typname = 'payment_status') then
    create type public.payment_status as enum
      ('created', 'authorized', 'captured', 'failed', 'refunded');
  end if;
end;
$$;

create table if not exists public.payments (
  id                 uuid primary key default gen_random_uuid(),
  booking_request_id uuid not null references public.booking_requests(id) on delete cascade,
  razorpay_order_id   text unique,
  razorpay_payment_id text unique,
  amount_inr         int not null check (amount_inr > 0),
  status             public.payment_status not null default 'created',
  method             text,
  error_code         text,
  error_description  text,
  -- Whole verified webhook body, so a disputed payment can be reconstructed
  -- from what Razorpay actually sent rather than from what we inferred.
  raw                jsonb,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists payments_booking_idx on public.payments (booking_request_id);

drop trigger if exists payments_touch_updated_at on public.payments;
create trigger payments_touch_updated_at
  before update on public.payments
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------- guests cannot self-quote ----

-- Replaces the v1 trigger. Every field below is a host decision or a payment
-- fact; a crafted insert must not be able to set any of them. Without this a
-- guest could submit a request that is already accepted, already paid, and
-- priced at one rupee.
create or replace function public.force_pending_on_insert()
returns trigger
language plpgsql
as $$
begin
  new.status          := 'pending';
  new.host_note       := null;
  new.quoted_total_inr := null;
  new.accepted_at     := null;
  new.hold_expires_at := null;
  new.decided_by      := null;
  new.nightly_rates   := null;
  new.subtotal_inr    := null;
  new.tax_inr         := null;
  new.total_inr       := null;
  new.deposit_inr     := null;
  new.deposit_paid_at := null;
  return new;
end;
$$;

-- ------------------------------------------------------------ hold expiry ----

-- An accepted request that nobody paid for must not hold the room forever.
-- Called opportunistically whenever availability is read, so the calendar is
-- always honest even without a scheduler; also safe to run from pg_cron.
create or replace function public.expire_stale_holds()
returns int
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  n int;
begin
  update public.booking_requests
     set status = 'expired'
   where status = 'accepted'
     and hold_expires_at is not null
     and hold_expires_at < now()
     and deposit_paid_at is null;
  get diagnostics n = row_count;
  return n;
end;
$$;

revoke all on function public.expire_stale_holds() from public;
grant execute on function public.expire_stale_holds() to anon, authenticated;

-- ---------------------------------------------------------- availability ----

-- Rewritten so that an accepted-but-unpaid hold also blocks the room, and so
-- that stale holds are cleared before the answer is computed.
create or replace function public.is_room_taken(p_room_id uuid, p_from date, p_to date)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.booking_requests b
    where b.room_id = p_room_id
      and b.status in ('accepted', 'confirmed')
      -- An expired hold that expire_stale_holds() has not swept yet must not
      -- block the room; this function is STABLE and cannot write.
      and not (b.status = 'accepted'
               and b.hold_expires_at is not null
               and b.hold_expires_at < now()
               and b.deposit_paid_at is null)
      and b.stay && daterange(p_from, p_to, '[)')
  ) or exists (
    select 1 from public.blocked_dates d
    where (d.room_id = p_room_id or d.room_id is null)
      and daterange(d.starts_on, d.ends_on, '[)') && daterange(p_from, p_to, '[)')
  );
$$;

revoke all on function public.is_room_taken(uuid, date, date) from public;
grant execute on function public.is_room_taken(uuid, date, date) to anon, authenticated;

-- Availability now carries the standing rate and occupancy, so the results
-- page can price a stay in one round trip instead of one per room. Dropped
-- and recreated rather than replaced: the return type is changing, and
-- CREATE OR REPLACE cannot change a function's output columns.
drop function if exists public.room_availability(date, date);

create function public.room_availability(
  from_date date,
  to_date   date
)
returns table (
  room_id         uuid,
  slug            text,
  name            text,
  room_number     int,
  has_kitchenette boolean,
  base_rate_inr   int,
  max_occupancy   int,
  is_available    boolean
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select
    rm.id,
    rm.slug,
    rm.name,
    rm.room_number,
    rm.has_kitchenette,
    rm.base_rate_inr,
    rm.max_occupancy,
    not public.is_room_taken(rm.id, from_date, to_date) as is_available
  from public.rooms rm
  where rm.is_active
  order by rm.sort_order, rm.room_number;
$$;

grant execute on function public.room_availability(date, date) to anon, authenticated;

-- ------------------------------------------------------------------ RLS ----

alter table public.settings       enable row level security;
alter table public.rate_overrides enable row level security;
alter table public.payments       enable row level security;

-- Prices and the deposit percentage are not secrets — the site has to show
-- them before anyone books.
drop policy if exists "settings are publicly readable" on public.settings;
create policy "settings are publicly readable"
  on public.settings for select to anon, authenticated using (true);

drop policy if exists "staff manage settings" on public.settings;
create policy "staff manage settings"
  on public.settings for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

drop policy if exists "rates are publicly readable" on public.rate_overrides;
create policy "rates are publicly readable"
  on public.rate_overrides for select to anon, authenticated using (true);

drop policy if exists "staff manage rates" on public.rate_overrides;
create policy "staff manage rates"
  on public.rate_overrides for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- Payments are staff-only. A guest checks payment state through their
-- reference via a definer function, never by reading this table.
drop policy if exists "staff read payments" on public.payments;
create policy "staff read payments"
  on public.payments for select to authenticated using (public.is_staff());

drop policy if exists "staff manage payments" on public.payments;
create policy "staff manage payments"
  on public.payments for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

